

service: weather-alerts-crud

provider:
  name: aws
  runtime: python3.8


functions:
  create-user:
    handler: handler.create_user
    events:
      - http:
          path: users/create
          method: post

  fetch-user:
    handler: handler.fetch_user
    events:
      - http:
          path: users/
          method: get

  fetch-user:
    handler: handler.fetch_user
    events:
      - http:
          path: users/{uid}
          method: get

  update-user:
    handler: handler.update_user
    events:
      - http:
          path: users/{uid}/update
          method: put

  remove-user:
    handler: handler.remove_user
    events:
      - http:
          path: users/{uid}/remove
          method: delete
  
  
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
